src/telemetry/client.ts

Our telemetry URL and key is still pointing at staging.
We want to send data to production instead of staging.
Confirmed in testing that the HTTP call still returns `200`.

Update the URL and keys for the telemetry endpoint

---

src/telemetry/client.ts

The endpoint prefers the JSON payload to use `records` instead of `Records`.
Change the JSON payload to use `records` instead of `Records`.
Confirmed with the data team that this is what we should do going forward.

Use records instead of Records

---

CONTRIBUTING.md

The current content of `CONTRIBUTING.md` is outdated and does not mention our requirement for a Developer Certificate of Origin (DCO).
Replaced the content of `CONTRIBUTING.md` with a new one that calls out that need to use `git commit -s`.
This is a documentation change.

Replace the current content with a mention of the DCO

---

src/utils/monitor.ts

When `docker` is not on the `PATH` the extension "hangs" and never completes its activation step.
If `docker` is not on the `PATH` then we will get an `'error'` event instead of an `'exit'` event with a non-zero exit code. We need to catch that case and then let the user know they need to install Docker Desktop.
If I use `docker2` instead we can see that the `'error'` event is hit.

Consider the case where docker is not on the PATH

---

src/extension.ts

If `docker` cannot be found on the `PATH` we do not send a `client_heartbeat` event.
We should still send a `client_heartbeat` event back if docker could not be found on the `PATH`. Fixed by handling the `"error"` event on the spawned process.
Reproduced by using `docker2` instead (which does not exist on my `PATH`).

Record the case where docker is not found on the PATH

---

src/utils/monitor.ts

If `docker` cannot be found on the `PATH` then the `docker desktop` CLI command will not complete. In that case our code is stuck because the promise is never resolved.
Catch the `"error"` event case where `docker` cannot be found on the `PATH` and resolving the promise will ensure that the user is prompted to install Docker Desktop.
Reproduced by temporarily changing the code to call `docker2 desktop version` (where `docker2 naturally cannot be found on my `PATH`).

Fail and notify the user if the docker desktop CLI cannot run

---

.vscode/settings.json

I saved a file but it didn't format it for me. :(
Asked @stanislavHamara for help and he mentioned adding some lines to the `settings.json`. :) This will help ensure consistency across the codebase and remove unnecessary conflicts between different versions of the file.
I confirm that I tested this change. :)

Enforce file formatting when a file is saved

---

src/extension.ts

The current approach does not give us enough flexibility over how we rollout the extension to our users.
Adding the user's operating system and the version of the extension will give us finer control over how we rollout the extension.
I tested it by toggling the feature flag around in Unleashed and swapping the context around with the following JavaScript file.
```JavaScript
const unleashLibrary = require('unleash-proxy-client');
const client = new unleashLibrary.UnleashClient({
url: 'https://hub.docker.com/v2/feature-flags/proxy/',
clientKey: 'changeme',
appName: 'vscode-extension',
});
client.updateContext({ properties: { operatingSystem: "linux", vscodeExtensionVersion: "0.0.21" } });
client.on('ready', () => {
console.log(client.isEnabled('VSCodeReleaseMarch2025'));
client.stop(); …
```

Add the operating system and the extension's version to the feature flag context

---

.github/workflows/build.yml

The [v0.0.21 build](https://github.com/docker/vscode-extension/actions/runs/13998712291) completed but no artifacts were uploaded to the [release](https://github.com/docker/vscode-extension/releases/tag/v0.0.21).
```
2025-03-21T18:43:45.5665414Z 🤔 Pattern 'docker-vscode-extension/docker-vscode-extension-darwin-x64-0.0.21.vsix' does not match any files.
2025-03-21T18:43:45.7462523Z Found release v0.0.21 (with id=207518691)
2025-03-21T18:43:45.8858277Z 🤔 docker-vscode-extension/docker-vscode-extension-darwin-x64-0.0.21.vsix not include valid file.
2025-03-21T18:43:45.8865151Z 🎉 Release ready at https://github.com/docker/vscode-extension/releases/tag/v0.0.21
2025-03-21T18:43:45.8972187Z Post job cleanup.
```
Fix the `files` attribute so that it references the right file to upload.
This is a …

Fix the path for uploading the artifact to the GitHub release

---

README.md

The `alt` text of all the images were unfortunately copied completely without rewriting them correctly.
Fixed the `alt` text. :)
Confirmed by checking the `alt` content in the browser debugger.

Fix the images' alt text

---

README.md
TELEMETRY.md

There is no clear breakdown of the telemetry that is being collected by the extension.
Create a dedicated `TELEMETRY.md` document to outline what kind of telemetry the extension collects.
This is a documentation change. :) See [here](https://github.com/docker/vscode-extension/blob/8ca56acf4b73c02bab2539be43ef19168fa91fe9/TELEMETRY.md) for a rendered version of the proposed `TELEMETRY.md` file.

Document what kind of telemetry is collected

---

README.md

After modifying the `docker.extension.experimental.release.march2025` setting, the user must restart VS Code in order for it to take effect but this is not documented.
Clarify this by adding a note about the required restart in `README.md`.
This is a documentation change. :)

Document the need to restart after changing the setting

---

.vscodeignore

1. `.github` workflows do not need to be included in the VSIX build.
2. `README.md` images are loaded from GitHub so they also do not need to be included in the VSIX build.
See #30.
Added the two aforementioned folders to `.vscodeignore`.
I ran `vsce package` with and without the command verified that the change works.
```
INFO  Files included in the VSIX:
docker-0.1.1.vsix
├─ [Content_Types].xml
├─ extension.vsixmanifest
└─ extension/
├─ Dockerfile [0.43 KB]
├─ LICENSE.txt [10.51 KB]
├─ SECURITY.md [1.82 KB]
├─ TELEMETRY.md [1.34 KB]
├─ changelog.md [0.48 KB]
├─ docker-compose.yml [0.37 KB]
├─ frontend.Dockerfile [0.02 KB]
├─ notes.md [0.52 KB]
├─ package.json [3.7 KB]
├─ readme.md [4.83 KB]
├─ tmp.js [0.72 KB]
├─ bin/
│  ├─ docker-language-server-darwin-arm64 [39.69 MB]
│  └─ …
```

Exclude unnecessary folders from the VSIX file

---

package.json

The "Build with Bake" command is showing up in the Command Palette and it does not run if you try to execute it.
We do not want this command to be available from the Command Palette so we should set its enablement attribute to "never". We may want to surface this in the future but we can cross that bridge when we get there.
This fix will resolve #32.
Verified that it no longer shows up in the Command Palette.

Hide "Build with Bake" command by default

---

src/utils/lsp/lsp.ts

When you have something like `golang:1.23.7`, hovering will show "Recommeneded tags" but nothing will be shown.
We have `<table>` HTML tags in the hover output. These will need the `supportHtml` property set in order for VS Code to render them instead of ignoring and stripping them out from the hovered content.
Closes #34.

Toggle supportHtml so that tables can be rendered in HTML

---

CHANGELOG.md
package.json
src/extension.ts

It would be helpful if we could scan images for CVEs with the `docker scout` command from the UI.
We will contribute a context menu item to Microsoft's extension to run `docker scout cves ...` on the selected image.

Add a menu item to scan images for CVEs with Docker Scout

---

CHANGELOG.md
src/utils/lsp/languageClient.ts

If both the Dockerfile Language Server and the Docker Language Server is running then some diagnostics will be duplicated across both language servers.
We will use a new experimental setting to suppress the duplicated errors from the Docker Language Server.
Closes #33.
We can see from this image that the `MaintainerDeprecated` error is not getting reported by twice but we still get the `JSONArgsRecommended` warning.

Suppress duplicated Dockerfile diagnostics

---

package.json

When searching for the extension, we have no description which can make it harder for people to understand why they should install the extension.
Add a description to `package.json`.
Debugging does not seem to change the description but this is where I see the text in other VS Code extensions so I believe this is the place.

Add a description to the extension

---

CHANGELOG.md
src/extension.ts

If you install the extension now, the Scout command will now work if the `docker.extension.experimental.release.march2025` setting is set to `featureFlag`.
Explicitly registering the command regardless of any feature flag or setting will help resolve this issue.
Fixes #44.

Register the Scout command regardless of any user setting

---

.github/scripts/check-commits.sh
.github/workflows/verify.yml

We would like all contributors to adhere to https://github.com/docker/vscode-extension/blob/main/CONTRIBUTING.md and sign their commits
Introduce a GHA that checks that a commit has been signed by either a "Signed-off" message or with a verified GPG, SSH, or S/MIME signature.
Tested:
- signed with GPG
- turned off GPG and signed off in a commit message
- removed a verified signature from a commit to trigger a GHA failure

Check commits are signed

---

.github/workflows/build.yml
CHANGELOG.md
README.md
build/downloader.mjs

Currently, any developer interested in looking at the VS Code extension has to download a binary of the Docker Language Server manually.
We can remove the aforementioned extra manual step by reusing `downloader.mjs` to download and place a binary of the Docker Language Server into the `bin` folder for us.
```
> docker@0.3.0 prepare
> npm run download:artifacts
> docker@0.3.0 download:artifacts
> node build/downloader.mjs
Downloading https://github.com/hashicorp/syntax/releases/download/v0.7.1/hcl.tmGrammar.json...
Saving to /workspaces/vscode-extension/syntaxes/hcl.tmGrammar.json...
Downloading https://github.com/docker/docker-language-server/releases/download/v0.2.0/docker-language-server-linux-arm64-v0.2.0...
Saving to /workspaces/vscode-extension/bin/docker-language-server-linux-arm64.. …
```

Download a binary of the language server with npm install

---

src/extension.ts

The `versionString` capture code currently assumes that we will get all of the data from stdout in one event.
Appending to `versionString` instead of assigning the event's data will ensure we have captured everything we want to capture.
There is unfortunately no easy way to test this.

Append to versionString instead of overriding it

---

package-lock.json
package.json
src/extension.ts

We still depend on `unleash-proxy-client` even though we do not use feature flags anywhere.
Remove the code... :)
Hard to prove this one... :S

Remove unleash-proxy-client as a dependency

---

CHANGELOG.md
TELEMETRY.md
src/utils/lsp/languageClient.ts

We currently only capture error counts but we have no context as to what kind of errors users are hitting.
We will add strict tests for messages to see if we recognize them. If we do then we'll include it in the telemetry as there is no ambiguity as to what kind of errors they are.
Confirmed in the debugger...

Capture error messages that we recognize

---

build/downloader.mjs

I forgot to update `downloader.mjs` for the builds... :(
Updated the numbers in `downloader.mjs`.
```
$ npm i
> docker@0.4.2 prepare
> npm run download:artifacts
> docker@0.4.2 download:artifacts
> node build/downloader.mjs
Downloading https://github.com/hashicorp/syntax/releases/download/v0.7.1/hcl.tmGrammar.json...
Saving to /Users/rcjsuen/code/docker/vscode-extension/syntaxes/hcl.tmGrammar.json...
Downloading https://github.com/docker/docker-language-server/releases/download/v0.3.0/docker-language-server-darwin-arm64-v0.3.0...
Saving to /Users/rcjsuen/code/docker/vscode-extension/bin/docker-language-server-darwin-arm64...
up to date, audited 621 packages in 3s
156 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```

Update downloader.mjs to get v0.3.0 of the language server

---

.github/workflows/build.yml

We currently only test against what `downloader.mjs` downloads. We should also test against the latest code in `docker/docker-language-server`.
Added another CI step to test the latest code in the repository.
This is a build change and cannot be verified easily.

Include the latest language server code in the tests

---

CHANGELOG.md
src/extension.ts

Currently, if `docker` is unavailable then the commands will fail silently instead of notifying the user.
Refactored the code so that it will always try to run the command even if it is doomed to fail.
Tested by temporarily renaming `docker` to `docker2` in the debugger.

Run docker commands even if they will fail

---

src/utils/lsp/languageClient.ts

There are still several error messages that are unknown.
Added some more error messages that are hardcoded into `vscode-languageclient` so we can flag them as being recognized and known.
Not easy to test this we will have to wait on the error telemetry to tell us more.

Add more error messages from vscode-languageclient

---

README.md

The table in the readme incorrectly called out Docker instead of the extension.
Fixed the typo... :)
This is a documentation change. The corrected file can be found [here](https://github.com/docker/vscode-extension/blob/833c5968c64f88f4b7382d143464f9153a0c5754/README.md).

Correct the README.md to note that it is the extension's requirement

---

CHANGELOG.md
src/extension.ts

If no workspace folder has been opened then the task cannot run because it does not know which folder to use as the working directory.
See https://github.com/microsoft/vscode-docker/issues/4552.
In this case, we should just use the user's home directory.
Fixes #76.

Run Scout task with the user's home directory

---

build/downloader.mjs

This doesn't change anything in the VS Code extension as it just includes a fix for an issue with the implementation of the specification (that affects other editors but VS Code itself seems to ignore the error).

Update to the 0.3.5 release of the language server

---

src/extension.ts
src/telemetry/client.ts
src/utils/lsp/languageClient.ts
src/utils/lsp/lsp.ts

The error data shows an `EACCES` for some users which may suggest that the binary is not executable. This may be because the file permissions has changed after the VSIX is extracted.
We will try to resolve this by explicitly checking and making the binary executable first.
Verified by changing the binary on my own computer to `644` and the language server was still able to start.

Check and try to make the language server binary executable

---

build/downloader.mjs
package.json

The new Container Tools extension will be releasing soon, and Docker DX should support it.
Fixes https://github.com/microsoft/vscode-containers/issues/38.
1. Support the new Container Tools extension by adding its view ID as a location to show the Scout CVEs command
2. Remove `ms-azuretools.vscode-docker` as a dependency--we are going to do a slow rollout of Container Tools that will temporarily require users to uninstall vscode-docker; we don't want that to also uninstall Docker DX.
3. Fixes an issue in the language server downloader script on Windows
1. Verified that the Scout CVEs command shows up in the intended location in the Container Tools extension
2. Straightforward enough to not verify :smile:
3. `npm i` works well on Windows

Support new Container Tools extension

---

.github/workflows/build.yml
CHANGELOG.md
README.md
build/downloader.mjs

Although we create VSIX builds for `linux-x64` and `linux-arm64`, we do not currently generate builds for `alpine-x64` or `alpine-arm64`.
The Docker Language Server binaries we are building are executable within Alpine Linux so it should be safe for us to generate VSIX builds for `alpine-x64` and `alpine-arm64`.
Closes #93.
To be verified...

Add support for generating VSIX builds for Alpine Linux

---

src/extension.ts
src/utils/monitor.ts
src/utils/os.ts
src/utils/prompt.ts
src/utils/settings.ts
src/utils/spawnDockerCommand.ts

If a user has an old version of docker that does not include e.g. `docker scout` or `docker ai` commands and the extension relies on them, we just error out "silently" in the console.
This PR introduces an error message being shown when a particular sub command of docker is not available.
TBD once we get a correct error message

CLI plugins error handling

---

README.md

Depending on what extensions a user has installed, they may find themselves with duplicated code completion suggestions or hover tooltips when editing a Compose file.
Documenting how to get rid of these duplicates will help improve our users' experience.
This is a documentation change. The rendered file can be viewed [here](https://github.com/docker/vscode-extension/blob/e3bbfe97ef7a063ca26959224ef5b9fde2fd257f/README.md).

Document how to remove duplicated Compose YAML support

---

src/utils/os.ts

The Docker Desktop check is not being executed correctly. It's running `docker docker desktop version` now.
When the code was refactored to use a generic `spawnDockerCommand` function, the removal of `'docker'` was missed so we were no longer running `docker desktop version` correctly. We also need to use the `onError` function to ensure that the code is executed correctly in the event that the docker binary cannot be found.
Verified that the code is working in a debugger.

Check for Docker Desktop correctly

---

CHANGELOG.md
src/extension.ts
src/utils/monitor.ts
src/utils/os.ts
src/utils/prompt.ts
src/utils/spawnDockerCommand.ts

If Scout is not available, users cannot use the "Scan for CVEs with Docker Scout" command.
If Scout is not available, we will suggest the user install Docker Desktop so that the Scout CLI plugin will get installed.

Prompt the user to install Docker Desktop if Scout is not found

---

TELEMETRY.md
src/extension.ts
src/telemetry/client.ts

The Visual Studio Code Marketplace is huge and different extensions offer different things. If multiple extensions offer the same features, then users may get duplicated results for hover tooltips or code completion suggestions.
As this extension has overlapping features with Microsoft's extensions and Red Hat's extension, knowing how often we are installed alongside these other extensions will help us understand usage patterns and how best to deduplicate similar features and educate users as to _why_ they are seeing duplicated results.
I've verified the payload in the debugger.

Record if certain extensions are installed

---

CHANGELOG.md
package.json
src/utils/lsp/languageClient.ts

Users may encounter duplicated Compose features when we bring in the latest changes from the Docker Language Server.
Created a new `docker.extension.experimental.composeSupport` to allow users to toggle the features as they desire.
Verified the behaviour in the debugger.

Create a global setting for toggling Compose editor features

---

TELEMETRY.md
package.json
src/extension.ts
src/utils/monitor.ts
src/utils/os.ts
src/utils/prompt.ts
src/utils/settings.ts

Previously, we would present a toast to the user to notify them that they would be seeing duplicates if Red Hat's YAML extension was installed. We will now auto-disable the Compose features if the YAML extension is installed.
If the user does some digging into the settings, they can read the description and learn more about the situation from the FAQ in our README.md. They can then proceed to opt-in to our Compose features manually with the full understanding of the implications of turning it on. If they follow the steps, they will also be able to disable the duplicates from Red Hat's extension.
The intent here is to give users full control over their Compose editing experience in Visual Studio Code. If they want to use Red Hat's YAML language server, they can. And if they want to use …

Change how Compose features are exposed

---

FAQ.md
README.md
package.json

Instead of repeatedly adding content to `README.md`, we will put our FAQs in a separate `FAQ.md` file to organize things better.

Document FAQs in a separate Markdown file

---

src/utils/lsp/languageClient.ts

We changed the name of the settings in #125 but forgot to make the corresponding change in `languageClient.ts`.

Disable Compose editing features correctly

---

CHANGELOG.md
build/downloader.mjs
package-lock.json
package.json

Updated to v0.10.2 of the Docker Language Server to include some bug fixes that have surfaced from yesterday's release.

Prepare for the v0.8.1 release

---

src/dap/config.ts

If the user tries to debug a Dockerfile when the debug setting is disabled, we still want to be able to warn them that the feature is disabled and that they can opt-in if desired.

Prompt the user about the disabled debug setting when launching

---

CHANGELOG.md
src/utils/lsp/lsp.ts

We do not need to suppress errors from the language server anymore as it is now pretty stable. Showing the errors will help inform our users and hopefully lead them to open bugs about any edge cases we have not been considering.

Show errors from the Docker Language Server

---

CHANGELOG.md
src/dap/config.ts

On Windows, there is a leading slash which causes problems. By using fsPath instead we'll get a regular C:\ path.
This will fix #181.

Fix working directory path for Buildx debugging

---

package.json
src/dap/config.ts

An additional property exists for the DAP launch configuration that
allows setting the `--builder` property for the `buildx` invocation.
This isn't normally possible through `args` because `args` places the
parameters after the invocation of `buildx` while the builder option has
to be before the `buildx` command.

dap: include additional launch configuration to customize the builder

---

.vscode/settings.json

Depending on a user's settings, saving the `package.json` file may cause the trailing newline character to be removed.
Explicitly setting Prettier as the formatter for JSON files will ensure formatting stays consistent and pull requests will not be opened with the trailing newline character removed by mistake.

Use Prettier for formatting JSON files

---

.github/workflows/build.yml

As the build no longer requires checking out the Docker Language Server's repository either, we should remove the use of the `working-directory` attribute to keep the build simple and easy to understand.

Remove working-directory from the build step

---

.github/workflows/build.yml

If the test fails, we should capture the screenshots and upload them as artifacts to help with debugging.

Upload test failure screenshots as artifacts

---

package-lock.json

```
axios  <1.12.0
Severity: high
Axios is vulnerable to DoS attack through lack of data size check - https://github.com/advisories/GHSA-4hjh-wcwx-xvwj
fix available via `npm audit fix`
node_modules/axios
brace-expansion  1.0.0 - 1.1.11 || 2.0.0 - 2.0.1
brace-expansion Regular Expression Denial of Service vulnerability - https://github.com/advisories/GHSA-v6h2-p8h4-qcjw
brace-expansion Regular Expression Denial of Service vulnerability - https://github.com/advisories/GHSA-v6h2-p8h4-qcjw
fix available via `npm audit fix`
node_modules/@eslint/eslintrc/node_modules/brace-expansion
node_modules/@humanwhocodes/config-array/node_modules/brace-expansion
node_modules/@vscode/vsce/node_modules/minimatch/node_modules/brace-expansion
node_modules/brace-expansion …
```

Run npm audit fix to update dependencies
